#!/bin/bash

git="/usr/local/bin/git"

is_git_repo() {
    $($git rev-parse --is-inside-work-tree &> /dev/null)
}

is_git_dir() {
    $($git rev-parse --is-inside-git-dir 2> /dev/null)
}

get_git_branch() {
    local branch_name

    branch_name=$($git symbolic-ref --quiet --short HEAD 2> /dev/null) ||
    branch_name=$($git rev-parse --short HEAD 2> /dev/null) ||
    branch_name="(unknown)"
    printf $branch_name
}

if is_git_repo && ! is_git_dir; then

	user=$(/usr/bin/whoami)
	branch=$(get_git_branch)

	log_file="/Users/$user/stats/git-commits.txt"

	repo_path=$($git rev-parse --show-toplevel)

	repo_name=$(/usr/bin/basename "$repo_path")

	_date=$(/bin/date +"%Y-%m-%d-%H-%M-%S")

	commit="$($git log --pretty=oneline -n 1 | cut -d ' ' -f2- )"

	/bin/echo "$_date [$repo_name:$branch] $commit" >> "$log_file"

fi
