#!/bin/bash

git=$(command -v git) || exit 0

is_git_repo() {
	[[ "$("$git" rev-parse --is-inside-work-tree 2> /dev/null)" == "true" ]]
}

is_git_dir() {
	[[ "$("$git" rev-parse --is-inside-git-dir 2> /dev/null)" == "true" ]]
}

get_git_branch() {
    local branch_name

	branch_name=$("$git" symbolic-ref --quiet --short HEAD 2> /dev/null) ||
	branch_name=$("$git" rev-parse --short HEAD 2> /dev/null) ||
    branch_name="(unknown)"
    printf '%s\n' "$branch_name"
}

if is_git_repo && ! is_git_dir; then

	branch=$(get_git_branch)

	log_dir="$HOME/stats"
	log_file="$log_dir/git-commits.txt"
	/bin/mkdir -p "$log_dir" || exit 0

	repo_path=$("$git" rev-parse --show-toplevel)

	repo_name=$(/usr/bin/basename "$repo_path")

	_date=$(/bin/date +"%Y-%m-%d-%H-%M-%S")

	commit=$("$git" log --format=%s -n 1)

	/bin/echo "$_date [$repo_name:$branch] $commit" >> "$log_file"

fi
